// Generated by https://quicktype.io

export interface IContractDetailsResponse {
	code: number
	status: string
	ok: boolean
	data: Data
}

export interface Data {
	id: number
	uuid: string
	PropertyId: number
	ClientId: number
	startDate: string
	endDate: string
	nroPartWater: string
	nroPartMuni: string
	nroPartAPI: string
	commission: number
	state: string
	amount: number
	description: string
	stamped: number
	fees: number
	warrantyInquiry: number
	createdAt: string
	updatedAt: string
	Client: Client
	Property: Property
	Assurances: Client[]
	PriceHistorials: Eventuality[]
	Eventualities: Eventuality[]
}

export interface Client {
	id: number
	uuid: string
	ContractId?: number
	fullName: string
	address: string
	phone: string
	email: string
	cuit: string
	obs: null | string
	createdAt: string
	updatedAt: string
	province?: string
	city?: string
}

export interface Eventuality {
	id: number
	uuid: string
	ContractId: number
	amount: number
	description?: string
	expiredDate?: string
	createdAt: string
	updatedAt: string
	year?: number
	porcent?: number
}

export interface Property {
	id: number
	uuid: string
	ZoneId: number
	PropertyTypeId: number
	OwnerId: number
	street: string
	number: string
	floor: string
	dept: string
	isFor: string
	state: string
	description: string
	createdAt: string
	updatedAt: string
}
