// Generated by https://quicktype.io

export interface IConfigResponse {
  results: number;
  code: number;
  status: string;
  ok: boolean;
  data: IConfig[];
}

export interface IConfig {
  id: number;
  key: string;
  value: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: null;
}
