// Generated by https://quicktype.io

export interface IdebtsResponse {
	results: number
	code: number
	status: string
	ok: boolean
	data: Idebt[]
}

export interface Idebt {
	// expenseDetails: ExpenseDetail[]
	id: number | string
	ContractId: number
	year: number
	amount: number
	month: number
	rent: boolean
	// total: number
	paid: boolean
	description: string
	debtParentId?: number | string
	createdAt: string
	updatedAt: string
	deletedAt: null
	// Contract: Contract
}

export interface Contract {
	id: number
	PropertyId: number
	ClientId: number
	startDate: string
	endDate: string
	commission: number
	state: string
	amount: number
	description: string
	stamped: number
	fees: number
	warrantyInquiry: number
	createdAt: string
	updatedAt: string
	deletedAt: null
	Property: Property
}

export interface Property {
	id: number
	ZoneId: number
	PropertyTypeId: number
	OwnerId: number
	street: string
	number: string
	floor: string
	dept: string
	isFor: string
	nroPartWater: null
	nroPartMuni: null
	nroPartAPI: null
	nroPartGas: null
	state: string
	description: string
	folderNumber: null
	createdAt: string
	updatedAt: string
	deletedAt: null
}

export interface ExpenseDetail {
	id: number
	description: string
	amount: number
	date: string
	ContractId: number
	createdAt: string
	updatedAt: string
}
