// Generated by https://quicktype.io

export interface IzonesResponse {
  results: number
  status: string
  code: number
  ok: boolean
  data: Izone[]
}

export interface Izone {
  id: number
  name: string
  createdAt?: string
  updatedAt?: string
}
